### ISSUE TITLE
Choosing a study to replicate

### ISSUE THREAD

**Issue by AliNasra** [AliNasra/Black-Box#1]
By May 14th, we ought to pick a paper and decide on the course. Asya shared an excellent selection of papers with the rest of the group members. In addition, Ayşe Hoca recommended the following reference. By next week's lecture, the abstract has to be written.
* [Proceedings of the Cognitive Science Society](https://escholarship.org/uc/cognitivesciencesociety/45/45)
* [ Computational Brain and Behavior](https://link.springer.com/search?new-search=true&query=*&search-within=Journal&sortBy=relevance&facet-journal-id=42113
)

**Comment by AliNasra** [comment]
I went over the 2 links and compiled a tentative list to choose from:
* How to handle the truth: A model of politeness as strategic truth-stretching: [link](https://escholarship.org/uc/item/952875jc)
* Children’s Cost-Benefit Analysis About Agents who Act for the Greater Good: [link](https://escholarship.org/uc/item/46174478)
* Do Children Learn English More Quickly When Their Native Language Is Similar To English?: [link](https://escholarship.org/uc/item/1z90478b)
* Groups are Better than Individuals at Solving Optimum Stopping Problems: [link](https://escholarship.org/uc/item/2pd5d3vk)
* Human music perception ability is not a sexually dimorphic trait: [link](https://escholarship.org/uc/item/4mz7t3f2)
* Machine learning-based measure of cognitive complexity explains variance in rank-ordered preference: [link](https://escholarship.org/uc/item/79g3t154)
* Scent of Poetry: Influence of Olfactory Imagery during Haiku Appreciation on Aesthetic Evaluation: [link](https://escholarship.org/uc/item/4pk522h1)
* Humans Adopt Different Exploration Strategies Depending on the Environment: [link](https://link.springer.com/article/10.1007/s42113-023-00178-1)
* Do men and women process happy and sad music alike: [link](https://www.researchgate.net/publication/379126808_Do_men_and_women_process_happy_and_sad_music_alike#:~:text=Happy%20music%20notably%20increases%20meta,greater%20efficiency%20in%20emotion%20regulation.)
* Gender Differences in Reliability and Guilt Ascriptions in the Context of Violent Crimes: [link](https://www.researchgate.net/publication/371857696_Gender_Differences_in_Reliability_and_Guilt_Ascriptions_in_the_Context_of_Violent_Crimes)
* A memory for goals model of prospective memory: [link](https://escholarship.org/uc/item/9m272017)
* People seek easily interpretable information: [link](https://escholarship.org/uc/item/5sm2b484)
* Habits of Mind: Reusing Action Sequences for Efficient Planning: [link](https://escholarship.org/uc/item/4gc7189b)
* Predicting consensus in legal document interpretation: [link](https://escholarship.org/uc/item/8rq5012j)
* Even those who perceive COVID-19 as low risk engage in infection prevention behavior in Japan: COVID-19 infection prevention behavior as a social norm: [link](https://escholarship.org/uc/item/1437c1v1)

**Comment by AliNasra** [comment]
The following papers seem to be the most promising:

1. How to handle the truth: A model of politeness as strategic truth-stretching [Code & Data](https://github.com/thelogicalgrammar/politeness)
2. Humans Adopt Different Exploration Strategies Depending on the Environment [Code & Data](https://github.com/tomferg/BanditComp)
3. Predicting consensus in legal document interpretation [data & Code](https://github.com/madiganbrodsky/vague_contracts)

**Comment by higurbuzz** [comment]
I scanned the links too and added the candidates here.

1. People seek easily interpretable information: [link](https://escholarship.org/uc/item/5sm2b484) (Ali's recommendation)
2. Distracted by Previous Experience: Integrating Selection History, Current Task Demands and Saliency in an Algorithmic Model [link](https://link.springer.com/article/10.1007/s42113-024-00197-6)
3. Traveling Salesperson Problem with Simple Obstacles: The Role of Multidimensional Scaling and the Role of Clustering [link](https://link.springer.com/article/10.1007/s42113-022-00155-0)

**Comment by higurbuzz** [comment]
We discussed the recommended papers and we decided on the following ones:

1. People seek easily interpretable information: [link](https://escholarship.org/uc/item/5sm2b484) 
2. Traveling Salesperson Problem with Simple Obstacles: The Role of Multidimensional Scaling and the Role of Clustering [link](https://link.springer.com/article/10.1007/s42113-022-00155-0)

As a backup paper, we propose:
How to handle the truth: A model of politeness as strategic truth-stretching [Code & Data](https://github.com/thelogicalgrammar/politeness)

**Comment by AliNasra** [comment]
We are moving forward with the paper [A model of politeness as strategic truth-stretching](https://escholarship.org/uc/item/952875jc).

**Comment by AliNasra** [comment]
Done!
